export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/Cellar/grep/3.1/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

alias yc='nocorrect yc '

